const LIGHT_PRIMARY_COLOR = "#ffffff";
const LIGHT_SECONDARY_COLOR = "#6B8E23";
const LIGHT_TERTIARY_COLOR = "#ffffff";

const DARK_PRIMARY_COLOR = "#393E46";
const DARK_SECONDARY_COLOR = "#082032";
const DARK_TERTIARY_COLOR = "#ffffff";


export {
    LIGHT_PRIMARY_COLOR,
    LIGHT_SECONDARY_COLOR,
    LIGHT_TERTIARY_COLOR,
    DARK_PRIMARY_COLOR,
    DARK_SECONDARY_COLOR,
    DARK_TERTIARY_COLOR
};
